typedef const unsigned int muh;
typedef const unsigned long long int lmuh;
typedef unsigned int var;
typedef unsigned long long int lvar;
void multiples();
void fibonacci();
void largest_prime_factor();
void smallest_divisible_number();
void difference();
void greatest_product();
